#
# Jekyll configuration
#
#exclude: ["vendor"]

markdown: kramdown

encoding: utf-8

gems:      ["jekyll-gist"]

collections:
    typescript:
            output: true
            permalink: /:path/index:output_ext
    languages:
            output: true
            permalink: /:path
    oop:
            output: true
            permalink: /oop/:path/index:output_ext
    functional:
            output: true
            permalink: /functional/:path/index:output_ext

oopFeatures:
- Class

functionalFeatures:
- TypeSafety
- TypeInference
- Generics
- Immutability
- StatelessProgramming
- PureFunction
- FirstClassFunction
- HigherOrderFunction
- PatternMatching

allFeatures:
- Access Control
- Arguments
- Array
- Block
- Class
- Class Method
- Closure
- Collections
- Constant
- Date
- Enumeration
- Error Handling
- Extension
- For
- Function
- Interface
- Generics
- Operator Function
- Optional
- Properties
- Protocol
- Range
- Structure
- Subscripts
- Switch
- this
- Trait
- Tuple
- Type
- Type Method
- TypeUnit
- Variable
- While
